/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest1 {

    @Test
    public void thisTestWillFail() {
        assertEquals("Expected true but got false", true, false); 
    }
}
